name: Build and deploy ASP.Net Core app to Azure Web App - CharityNavigator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./backend/backend.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./backend/backend.csproj -c Release -o ./published_app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./published_app

deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          subscription-id: ${{ secrets.2da8e42b-23b1-40cc-864f-173aa4cbaacd }}


      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CharityNavigator'  # Replace with your Azure App Service name
          slot-name: 'Production'  # Replace with your slot name if applicable
          package: ./published_app  # Path to the published app
